function base64_encode(data){var b64='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';var o1,o2,o3,h1,h2,h3,h4,bits,i=0,ac=0,enc='',tmp_arr=[];if(!data){return data;}
data=unescape(encodeURIComponent(data));do{o1=data.charCodeAt(i++);o2=data.charCodeAt(i++);o3=data.charCodeAt(i++);bits=o1<<16|o2<<8|o3;h1=bits>>18&0x3f;h2=bits>>12&0x3f;h3=bits>>6&0x3f;h4=bits&0x3f;tmp_arr[ac++]=b64.charAt(h1)+b64.charAt(h2)+b64.charAt(h3)+b64.charAt(h4);}while(i<data.length);enc=tmp_arr.join('');var r=data.length%3;return(r?enc.slice(0,r-3):enc)+'==='.slice(r||3);}
function decode_base64(s){s=s.substring(4);var e={},i,k,v=[],r='',w=String.fromCharCode;var n=[[65,91],[97,123],[48,58],[43,44],[47,48]];for(z in n){for(i=n[z][0];i<n[z][1];i++){v.push(w(i));}}
for(i=0;i<64;i++){e[v[i]]=i;}
for(i=0;i<s.length;i+=72){var b=0,c,x,l=0,o=s.substring(i,i+72);for(x=0;x<o.length;x++){c=e[o.charAt(x)];b=(b<<6)+c;l+=6;while(l>=8){r+=w((b>>>(l-=8))%256);}}}
return r;}
function trim(str){return str.replace(/^\s+|\s+$/g,"");}
function randomString(length,chars){var result='';for(var i=length;i>0;--i)result+=chars[Math.round(Math.random()*(chars.length-1))];return result;}
var guid=randomString(32,'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ');$.qq=function(name,url){if(!url){url=window.location.href;}
var results=new RegExp('[\\?&]'+name+'=([^&#]*)').exec(url);if(!results){return undefined;}
return results[1]||undefined;}
var pml=-1;function showpl(b,c,d){var $pLink=$(b);var tthis=b;var StatusP=$pLink.html();var b=$("."+d).index(b);if(StatusP==="Play"){$('.playerr').html('').hide();$('.play').attr("class",'play');$('.play').html('Play');$pLink.html('Stop');$pLink.attr("class",'play pstop');$pLink.attr("title",'');$(tthis).parent().parent().find('.playerr').html("<object type='application/x-shockwave-flash' data='player_mp3_mini.swf?mp3=http://www.goear.com/action/sound/get/"+c+"&amp;autoplay=1' width='200' height='20' id='dewplayer-1'><param name='wmode' value='transparent'><param name='movie' value='player_mp3_mini.swf?mp3=http://www.goear.com/action/sound/get/"+c+"&amp;autoplay=1'></object>").show()}else{$('.play').attr("class",'play');$('.play').html('Play');if(pml!=-1)$(".playerr:eq("+pml+")").html('').hide();}
pml=b;return false}
var songmirror=$.qq('q');var source2='http://www.songmirror.com/search.php?q='+songmirror;var myArray=['http://d2.mycoolmp3.net/cool/request.php','http://savefil.es/request.php','/curl/mp3/request.php','http://mycoolmp3.com/request.php','http://www.musicsheriff.biz/request.php','http://www.mp3sheriff.eu/request.php','http://mp3ale.biz/request.php','https://www.ascultaperepeat.com/request.php','http://www.365mp3.eu/request.php','http://mp3lover.in/request.php','http://www.vitanclub.net/request.php','http://www.songmirror.com/request.php'];var req=myArray[Math.floor(Math.random()*myArray.length)];var _c=false;var NEWDOWNLOAD={};NEWDOWNLOAD.Status=function(obj,title){$.ajax({url:'mp3.php?status=status',async:true,cache:false,data:{id:obj.hash},dataType:'json',success:function(a){switch(parseInt(a.progress)){case 1:case 2:$('#status').html('<img src="css/img/loader.gif" alt="" /> Please be patient, our servers are a little bit overloaded...your file will be ready in few seconds!!');break;case 3:_c=true;$('#status').html('');$('#dld').attr('href','get.php?r='+base64_encode(parseInt((a.sid))+'&key='+obj.hash+'&title='+encodeURIComponent(title)));$('#highspeed').attr('href','get.php?h='+base64_encode(title));$('#extern').attr('href','ext2.php?f='+base64_encode(title));$('#player').show();break;case 5:_c=true;$('#status').html('<div style="color:#f11;">An error has occured. Please try to download a different song.</div>');break;default:_c=false;break;}
if(_c==false){window.setTimeout(function(){console.log('refresh');NEWDOWNLOAD.Status(obj,title)},3000)}}})}
NEWDOWNLOAD.Validate=function(e,title){$('#source2').attr('href',source2);var f='mp3';$.ajax({url:'mp3.php?status=validate',async:true,cache:false,data:{v:e,f:f,sig:1337},dataType:'json',success:function(a){if(-1<a.error.indexOf(5)){$("#status").html('An error has occured. Please try to download a different song or press download again.');return false}
NEWDOWNLOAD.Status(a,title)}});}
NEWDOWNLOAD.init=function(){return'<div id="status" style="color:#f11;font-weight:bold;margin:5px"><img src="css/img/loader.gif" alt="" /> Loading mp3 file please wait...or you can <a href="javascript:;" id="source2" target="_blank">click here</a> to download from songmirror</div>'+'<div class="downButtons" style="display:none;margin:5px" id="player">'+'<b class="red">Choose a server to download your song!</b>'+'<br />'+'<a rel="nofollow" class="dhs dss" id="highspeed" href="javascript:;" target="_blank"><span style="font-size:12px">HighSpeed Download</span></a>'+'<a rel="nofollow" class="ext dss" target="_blank" id="extern" href="javascript:;">External Download</a>'+'<a rel="nofollow" target="_blank" class="dr dss" id="dld" href="javascript:;"><span style="font-size:12px">Regular Download</span></a>'+'</div>';}
function dd(b,c,d){var tthis=b;var b=$("."+d).index(b);$(".playerr").html('');$(".playerr").eq(b).show();var $containerM=$(".playerr:eq("+b+")");$('.play').attr("class",'play');$('.play').html('Play');$(tthis).parent().parent().find('.playerr').html("<div id=\"status\" style=\"color:#f11;font-weight:bold;margin:5px\"><img src='css/img/loader.gif'/></div>").show();var stitle=$(tthis).parent().parent().find('.rest').text().replace(/ +(?= )/g,'');$(".playerr:eq("+b+")").html(NEWDOWNLOAD.init());cool.download(decode_base64(c),stitle);return false;}
if(top.location!=self.location){top.location=self.location.href}
function makeAction(e){e=e.replace(/[^\w\s]|(.)(?=\1)/g," ").replace(/\s{2,}/g," ");e=e.replace(/\W/g,"+");alert(e)}
function sterilizeInput(e){e=e.replace("download","");e=e.replace("mp3","");e=e.replace("free","");var t;if(t=e.match(/[\w]+/g)){var n=t.join("+");n="s.php?q="+n;window.location=n.toLowerCase();}}
$(window).bind("load",function(){setTimeout(function(){$('#ad728h').html('<iframe id="ad728hh" src="//go.padsdel.com/?id=126676&t=iframe&var=488" style="width:728px;height:90px;border:0;overflow:hidden;"></iframe>');$('#ad300').html('<iframe id="ad300x" src="//go.padsdel.com/?id=126667&t=iframe&var=488" style="width:300px;height:250px;border:0;overflow:hidden;"></iframe>');$('#ad728f').html('<iframe id="ad728ff" src="http://go.padsdel.com/?id=126676&t=iframe&var=488" style="width:728px;height:90px;border:0;overflow:hidden;"></iframe>');},1000);});if(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)||(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.platform))){$(window).bind("load",function(){setTimeout(function(){$('#ad728f').attr("style",'width:302px;');$('#container_bottom').attr("style",'width:320px;');$('#ad728h').html('<iframe id="ad300x2" src="//go.padsdel.com/?id=126667&t=iframe&var=488" style="width:300px;height:250px;border:0;overflow:hidden;"></iframe>');$('#ad728f').html('<iframe id="ad300x2f" src="//go.padsdel.com/?id=126667&t=iframe&var=488" style="width:300px;height:250px;border:0;overflow:hidden;"></iframe>');},1000);});}
$(".play, .download").each(function(){var el=$(this);el.click(function(){$('#ad728hh',parent.document).attr('src',$('#ad728hh',parent.document).attr('src'));$('#ad300x',parent.document).attr('src',$('#ad300x',parent.document).attr('src'));$('#ad300x2',parent.document).attr('src',$('#ad300x2',parent.document).attr('src'));$('#ad300x2f',parent.document).attr('src',$('#ad300x2',parent.document).attr('src'));$('#ad728ff',parent.document).attr('src',$('#ad728ff',parent.document).attr('src'));});});$('.inchide').on('click',function(){$(this).closest('div').remove();});if(typeof console=="undefined"){this.console={log:function(){},info:function(){},error:function(){},warn:function(){}};};function share(pageURL,title,w,h){var left=(screen.width-w)/2;var top=(screen.height-h)/4;var targetWin=window.open(pageURL,title,'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);}
function PlayRadio(){var e=document.getElementById("radiolist");var radiourl=e.options[e.selectedIndex].value;var radio=e.options[e.selectedIndex].text;document.getElementById("radioplr").innerHTML='<audio style="margin-top:10px" src="'+radiourl+'" type="audio/mp3" autoplay="true" loop="true" preload="auto" controls><code>Your browser doesn\'t support audio tags</code></audio><br /><b>'+radio+'</b> music radio';}
$(function(){});var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){var t="";var n,r,i,s,o,u,a;var f=0;e=Base64._utf8_encode(e);while(f<e.length){n=e.charCodeAt(f++);r=e.charCodeAt(f++);i=e.charCodeAt(f++);s=n>>2;o=(n&3)<<4|r>>4;u=(r&15)<<2|i>>6;a=i&63;if(isNaN(r)){u=a=64}else if(isNaN(i)){a=64}t=t+this._keyStr.charAt(s)+this._keyStr.charAt(o)+this._keyStr.charAt(u)+this._keyStr.charAt(a)}return t},decode:function(e){var t="";var n,r,i;var s,o,u,a;var f=0;e=e.replace(/[^A-Za-z0-9\+\/\=]/g,"");while(f<e.length){s=this._keyStr.indexOf(e.charAt(f++));o=this._keyStr.indexOf(e.charAt(f++));u=this._keyStr.indexOf(e.charAt(f++));a=this._keyStr.indexOf(e.charAt(f++));n=s<<2|o>>4;r=(o&15)<<4|u>>2;i=(u&3)<<6|a;t=t+String.fromCharCode(n);if(u!=64){t=t+String.fromCharCode(r)}if(a!=64){t=t+String.fromCharCode(i)}}t=Base64._utf8_decode(t);return t},_utf8_encode:function(e){e=e.replace(/\r\n/g,"\n");var t="";for(var n=0;n<e.length;n++){var r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r)}else if(r>127&&r<2048){t+=String.fromCharCode(r>>6|192);t+=String.fromCharCode(r&63|128)}else{t+=String.fromCharCode(r>>12|224);t+=String.fromCharCode(r>>6&63|128);t+=String.fromCharCode(r&63|128)}}return t},_utf8_decode:function(e){var t="";var n=0;var r=c1=c2=0;while(n<e.length){r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r);n++}else if(r>191&&r<224){c2=e.charCodeAt(n+1);t+=String.fromCharCode((r&31)<<6|c2&63);n+=2}else{c2=e.charCodeAt(n+1);c3=e.charCodeAt(n+2);t+=String.fromCharCode((r&15)<<12|(c2&63)<<6|c3&63);n+=3}}return t}}
var d=false;var c=false;var api='cool2.php';var cool={status:function(cmd,title){$.post(api,cmd,function(a){var res=a.result;switch(res.status){case'ok':case'start':case'download':$('#status').html('<img src="css/img/loader.gif" alt="" /> Please be patient, our servers are a little bit overloaded...your file will be ready in few seconds!!');break;case'processFile':$('#status').html('<img src="css/img/loader.gif" alt="" /> Please be patient, our servers are a little bit overloaded...your file will be ready in few seconds!!');break;case'processFileEnd':c=true;cool.download(cmd['args[keyHash]'],title);break;case'processFileStart':$('#status').html('<img src="css/img/loader.gif" alt="" /> Please be patient, our servers are a little bit overloaded...your file will be ready in few seconds!!');break;case'failed':c=true;$("#status").html('An error has occured. Please try to download a different song or press download again.');break;}
if(!c){window.setTimeout(function(){cool.status(cmd,title)},3000)}});},process:function(cmd,title){$.post(api,cmd,function(a){var res=a.result;var id=res.id;cmd['args[id]']=id;cmd['cmd']='getStatusVideo';cool.status(cmd,title);});},download:function(e,title){$.post(api,{'cmd':'validate','args[volume]':0,'args[videoResolution]':-1,'args[urlEntryUser]':'http://www.youtube.com/watch?v='+e,'args[startFrom]':-1,'args[requestExt]':'mp3','args[nbRetry]':0,'args[fromConvert]':'videoconverter','args[endTo]':-1,'args[dummy]':1,'args[custom_resy]':-1,'args[custom_resx]':-1,'args[channel]':'stereo','args[audioFrequency]':0,'args[audioBitrate]':0,'args[aspectRatio]':-1,'args[advSettings]':'false'},function(a){var obj=a.result;switch(obj.status){case'normal':c=false;var cmd={'cmd':'processVideo','args[volume]':0,'args[videoResolution]':-1,'args[urlEntryUser]':'http://www.youtube.com/watch?v='+e,'args[title]':title,'args[startFrom]':-1,'args[sid]':obj.sid,'args[serverUrl]':obj.serverUrl,'args[serverId]':obj.serverId,'args[requestExt]':'mp3','args[nbRetry]':0,'args[keyHash]':obj.keyHash,'args[id]':-1,'args[fromConvert]':'videoconverter','args[endTo]':-1,'args[dummy]':1,'args[custom_resy]':-1,'args[custom_resx]':-1,'args[channel]':'stereo','args[audioFrequency]':0,'args[audioBitrate]':0,'args[aspectRatio]':-1,'args[advSettings]':'false'}
cool.process(cmd,title);break;case'incache':c=true;$('#status').html('');$('#dld').attr('href','get.php?r='+guid+obj.videoToDownloadDecoded+'&title='+base64_encode(title));$('#highspeed').attr('href','get.php?h='+base64_encode(title));$('#extern').attr('href','ext2.php?f='+base64_encode(title));$('#player').show();$('.downButtons').show();break;case'failed':$('#status').html('<div style="color:#f11;">An error has occured. Please try to download a different song.</div>');break;}});}}
$(document).ready(function(){sortby="";$(".sortby").click(function(){sortby=$(this).attr("id");$(".breadcrumb").find(".sortby").removeClass("bold");$(".breadcrumb").find("#"+sortby).addClass("bold");if(sortby=="id"){$.tinysort.defaults.order="asc"}else{$.tinysort.defaults.order="desc"}
$(".sortare").tsort({attr:"data-"+sortby})});})